---
# tasks file for testrole
- name: Ansible delete file glob
  find:
    paths: /home/ubuntu/test/
    patterns: "*test*"
  register: files_to_delete

- name: Ansible remove file glob
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"

# - name: Delete directory
#   shell: rm -rf /home/ubuntu/test*